### PR TITLE
feat(streaming): make baseurl configuration and add stream output

### PR DESCRIPTION
**Pull request by pc-dong**

### CODE REVIEW

**Comment by briansunter** [comment]
Just tested it and the streaming seems to work. Looks really good and would be great to have the streaming!

Some comments:
- Fix merge conflicts from last merge
- Use baseurl config from earlier merged PR
- Remove style changes
- Fix tests or remove
- Remove commented out code and console logs

Thanks for this contribution!

**Comment by pc-dong** [comment]
Fixed merge conflicts AND Remove tests

**Comment by briansunter** [comment]
Looks great and works really well. Really appreciate this contribution!

**Comment by mrdavidlaing** [comment]
@pc-dong Your streaming contribution puts a huge smile on my face every time I hit `<cmd>-j` and the answer come streaming in.

**Pull request merged**
